export const CLASSES = {
  hextech: 'Хекстековый',
  colossus: 'Колосс',
  syndicate: 'Преступник',
  arcanist: 'Адепт магии',
  scrap: 'Собиратель',
  bodyguard: 'Телохранитель',
  debonair: 'Галантный',
  enforcer: 'Миротворец',
  rival: 'Соперница',
  bruiser: 'Громила',
  chemtech: 'Химтековый',
  challenger: 'Задира',
  'yordle-lord': 'Йордл-повелитель',
  yordle: 'Йордл',
  socialite: 'Тусовщик',
  mercenary: 'Наёмник',
  twinshot: 'Дуплет',
  striker: 'Вышибала',
  innovator: 'Изобретатель',
  transformer: 'Гений',
  clockwork: 'Механический',
  sniper: 'Снайпер',
  scholar: 'Учёный',
  mutant: 'Мутант',
  assassin: 'Убийца'
}

export const CLASS_EMBLEMS = {
  Хекстековый: require('@/static/images/classes/hextech.png'),
  Колосс: require('@/static/images/classes/colossus.png'),
  Преступник: require('@/static/images/classes/syndicate.png'),
  'Адепт магии': require('@/static/images/classes/arcanist.png'),
  Собиратель: require('@/static/images/classes/scrap.png'),
  Телохранитель: require('@/static/images/classes/bodyguard.png'),
  Галантный: require('@/static/images/classes/debonair.png'),
  Миротворец: require('@/static/images/classes/enforcer.png'),
  Соперница: require('@/static/images/classes/rival.png'),
  Громила: require('@/static/images/classes/bruiser.png'),
  Химтековый: require('@/static/images/classes/chemtech.png'),
  Задира: require('@/static/images/classes/challenger.png'),
  'Йордл-повелитель': require('@/static/images/classes/yordle-lord.png'),
  Йордл: require('@/static/images/classes/yordle.png'),
  Тусовщик: require('@/static/images/classes/socialite.png'),
  Наёмник: require('@/static/images/classes/mercenary.png'),
  Дуплет: require('@/static/images/classes/twinshot.png'),
  Вышибала: require('@/static/images/classes/striker.png'),
  Изобретатель: require('@/static/images/classes/innovator.png'),
  Гений: require('@/static/images/classes/transformer.png'),
  Механический: require('@/static/images/classes/clockwork.png'),
  Снайпер: require('@/static/images/classes/sniper.png'),
  Учёный: require('@/static/images/classes/scholar.png'),
  Мутант: require('@/static/images/classes/mutant.png'),
  Убийца: require('@/static/images/classes/assassin.png')
}
